### ISSUE TITLE
Add profile

### ISSUE THREAD

**Issue by pnutzz-0207** [AY2122S2-CS2103T-W12-2/tp#3]
As a school admin/TA/student, I can add someone’s contact information, so that I can update my contact or contact him/her when needed

**Comment by junjieteoh** [comment]
- As a user who does not program that much, I can easily add someone's contact information in the contact book through the GUI, so that I do not need to learn the complicated CLI commands. 
- As a user who prefer keyboard, I can easily add someone's contact information so that the process can be more efficient.
